// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

/*
Package info is a generated protocol buffer package.

It is generated from these files:
	info.proto

It has these top-level messages:
	InfoReq
	InfoRep
*/
package info

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InfoReq struct {
	ID int64 `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *InfoReq) Reset()                    { *m = InfoReq{} }
func (m *InfoReq) String() string            { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()               {}
func (*InfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InfoReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type InfoRep struct {
	RetCode string `protobuf:"bytes,1,opt,name=retCode" json:"retCode,omitempty"`
	RetMsg  string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg,omitempty"`
}

func (m *InfoRep) Reset()                    { *m = InfoRep{} }
func (m *InfoRep) String() string            { return proto.CompactTextString(m) }
func (*InfoRep) ProtoMessage()               {}
func (*InfoRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InfoRep) GetRetCode() string {
	if m != nil {
		return m.RetCode
	}
	return ""
}

func (m *InfoRep) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoReq)(nil), "info.InfoReq")
	proto.RegisterType((*InfoRep)(nil), "info.InfoRep")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Info service

type InfoClient interface {
	GetInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRep, error)
}

type infoClient struct {
	cc *grpc.ClientConn
}

func NewInfoClient(cc *grpc.ClientConn) InfoClient {
	return &infoClient{cc}
}

func (c *infoClient) GetInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRep, error) {
	out := new(InfoRep)
	err := grpc.Invoke(ctx, "/info.Info/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Info service

type InfoServer interface {
	GetInfo(context.Context, *InfoReq) (*InfoRep, error)
}

func RegisterInfoServer(s *grpc.Server, srv InfoServer) {
	s.RegisterService(&_Info_serviceDesc, srv)
}

func _Info_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/info.Info/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServer).GetInfo(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Info_serviceDesc = grpc.ServiceDesc{
	ServiceName: "info.Info",
	HandlerType: (*InfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Info_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "info.proto",
}

func init() { proto.RegisterFile("info.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcc, 0x4b, 0xcb,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x24, 0xb9, 0xd8, 0x3d, 0xf3,
	0xd2, 0xf2, 0x83, 0x52, 0x0b, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x98, 0x83, 0x98, 0x32, 0x5d, 0x94, 0xac, 0x61, 0x52, 0x05, 0x42, 0x12, 0x5c, 0xec, 0x45, 0xa9,
	0x25, 0xce, 0xf9, 0x29, 0xa9, 0x60, 0x79, 0xce, 0x20, 0x18, 0x57, 0x48, 0x8c, 0x8b, 0xad, 0x28,
	0xb5, 0xc4, 0xb7, 0x38, 0x5d, 0x82, 0x09, 0x2c, 0x01, 0xe5, 0x19, 0xe9, 0x73, 0xb1, 0x80, 0x34,
	0x0b, 0xa9, 0x73, 0xb1, 0xbb, 0xa7, 0x96, 0x80, 0x99, 0xbc, 0x7a, 0x60, 0xdb, 0xa1, 0xd6, 0x49,
	0xa1, 0x70, 0x0b, 0x92, 0xd8, 0xc0, 0xae, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xec, 0x75,
	0x1e, 0x6d, 0xa3, 0x00, 0x00, 0x00,
}
